# Some Additional Info on Top News

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_path = '../data/processed/weekly_top_25_material_conflict.csv'
df = pd.read_csv(data_path)

In [4]:
df.head()

,mention_week,conflict_country_name,conflict_continent,material_conflict_mentions,material_conflict_unique_events,material_conflict_mentions_weighted
0,2015-02-16,United States,North America,98192,33319,9.270113
1,2015-02-16,Ukraine,Europe,22242,8985,9.938102
2,2015-02-16,Syria,Asia,15591,6371,5.426069
3,2015-02-16,Russia,Europe,12586,5546,5.666502
4,2015-02-16,Australia,Oceania,12322,2817,1.164875

In [5]:
# drop columns ['material_conflict_unique_events', 'material_conflict_mentions_weighted']
df = df.drop(columns=['material_conflict_unique_events', 'material_conflict_mentions_weighted'])
df.head()

,mention_week,conflict_country_name,conflict_continent,material_conflict_mentions
0,2015-02-16,United States,North America,98192
1,2015-02-16,Ukraine,Europe,22242
2,2015-02-16,Syria,Asia,15591
3,2015-02-16,Russia,Europe,12586
4,2015-02-16,Australia,Oceania,12322

In [6]:
# For each 'mention_week' keep rows with highest 5 'material_conflict_mentions'
df_filtered = df.groupby('mention_week').apply(lambda x: x.nlargest(5, 'material_conflict_mentions')).reset_index(drop=True)
df_filtered.head()

C:\Users\HEW14SDQ1006NL\AppData\Local\Temp\ipykernel_42764\4028717995.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_filtered = df.groupby('mention_week').apply(lambda x: x.nlargest(5, 'material_conflict_mentions')).reset_index(drop=True)

,mention_week,conflict_country_name,conflict_continent,material_conflict_mentions
0,2015-02-16,United States,North America,98192
1,2015-02-16,Ukraine,Europe,22242
2,2015-02-16,Syria,Asia,15591
3,2015-02-16,Russia,Europe,12586
4,2015-02-16,Australia,Oceania,12322

In [7]:
df_filtered.head(10)

,mention_week,conflict_country_name,conflict_continent,material_conflict_mentions
0,2015-02-16,United States,North America,98192
1,2015-02-16,Ukraine,Europe,22242
2,2015-02-16,Syria,Asia,15591
3,2015-02-16,Russia,Europe,12586
4,2015-02-16,Australia,Oceania,12322
5,2015-02-23,United States,North America,220589
6,2015-02-23,Russia,Europe,50240
7,2015-02-23,Syria,Asia,41214
8,2015-02-23,Iraq,Asia,36043
9,2015-02-23,Ukraine,Europe,29132

In [8]:
# Add 'google_search' column 
newspaper_sources = ['apnews.com', 'reuters.com', 'reuters.com', 'npr.org', 'pbs.org', 'bbc.com', 'dw.com', 'aljazeera.com']

# Ensure your date column is actually datetime objects (not strings)
df_filtered['mention_week'] = pd.to_datetime(df_filtered['mention_week'])

# This creates a list of random sources the same length as your DataFrame
random_choices = np.random.choice(newspaper_sources, size=len(df_filtered))

# We cast to string and take the date part only (YYYY-MM-DD)
start_date = df_filtered['mention_week'].dt.strftime('%Y-%m-%d')
end_date = (df_filtered['mention_week'] + pd.Timedelta(days=7)).dt.strftime('%Y-%m-%d')

df_filtered['google_search'] = (
    "https://www.google.com/search?q=site:" + 
    random_choices + 
    "+" + df_filtered['conflict_country_name'] + 
    "+news+after:" + start_date + 
    "+before:" + end_date
)

# Optional: Print one to verify
print(df_filtered['google_search'].iloc[0])

https://www.google.com/search?q=site:aljazeera.com+United States+news+after:2015-02-16+before:2015-02-23

In [9]:
df_filtered.head(10)

,mention_week,conflict_country_name,conflict_continent,material_conflict_mentions,google_search
0,2015-02-16,United States,North America,98192,https://www.google.com/search?q=site:aljazeera...
1,2015-02-16,Ukraine,Europe,22242,https://www.google.com/search?q=site:apnews.co...
2,2015-02-16,Syria,Asia,15591,https://www.google.com/search?q=site:apnews.co...
3,2015-02-16,Russia,Europe,12586,https://www.google.com/search?q=site:apnews.co...
4,2015-02-16,Australia,Oceania,12322,https://www.google.com/search?q=site:bbc.com+A...
5,2015-02-23,United States,North America,220589,https://www.google.com/search?q=site:reuters.c...
6,2015-02-23,Russia,Europe,50240,https://www.google.com/search?q=site:reuters.c...
7,2015-02-23,Syria,Asia,41214,https://www.google.com/search?q=site:pbs.org+S...
8,2015-02-23,Iraq,Asia,36043,https://www.google.com/search?q=site:bbc.com+I...
9,2015-02-23,Ukraine,Europe,29132,https://www.google.com/search?q=site:dw.com+Uk...

In [10]:
# df_filtered.to_csv('../data/processed/weekly_top_5_material_conflict_with_search.csv', index=False)

In [11]:
path_news = '../data/processed/news_articles.CSV'
df_news = pd.read_csv(path_news, sep=';', encoding='ANSI')
df_news.head()

  mention_week info  url marked
0   16/02/2015  NaN  NaN    NaN
1   23/02/2015  NaN  NaN    NaN
2   02/03/2015  NaN  NaN    NaN
3   09/03/2015  NaN  NaN    NaN
4   16/03/2015  NaN  NaN    NaN

In [12]:
# row where mention_week is '2025-06-16'
df_news[df_news['mention_week'] == '23/06/2025']

,mention_week,info,url,marked
540,23/06/2025,NO DATA AVAILABLE DUE TO MULTIPLE GDELT INFRAC...,https://www.linkedin.com/posts/kalevleetaru_we...,NaN

In [13]:
# Generate a list of all mondays starting from 2015-02-16 to 2026-01-12
all_dates = pd.date_range(start='2015-02-16', end='2026-01-12', freq='W-MON')

In [14]:
unique_dates = df_filtered['mention_week'].sort_values().unique()

# verify all dates are in unique_dates (= that we have data for all weeks)
for date in all_dates:
    if date not in unique_dates:
        print(f"Missing date: {date}")

Missing date: 2025-06-16 00:00:00
Missing date: 2025-06-23 00:00:00

In [15]:
# they should be converted in the same type for comparison
all_dates_str = [date.strftime('%Y-%m-%d') for date in all_dates]
unique_dates_str = [date.strftime('%Y-%m-%d') for date in unique_dates]
for date in all_dates_str:
    if date not in unique_dates_str:
        print(f"Missing date: {date}")

Missing date: 2025-06-16
Missing date: 2025-06-23

In [16]:
df_news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570 entries, 0 to 569
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mention_week  570 non-null    object
 1   info          190 non-null    object
 2   url           190 non-null    object
 3   marked        58 non-null     object
dtypes: object(4)
memory usage: 17.9+ KB

In [17]:
# Convert df_news 'mention_week' to datetime (Warning: right now it's in dd/mm/yyyy format but I want yyyy-mm-dd)
df_news['mention_week'] = pd.to_datetime(df_news['mention_week'], format='%d/%m/%Y')
df_news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570 entries, 0 to 569
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mention_week  570 non-null    datetime64[ns]
 1   info          190 non-null    object
 2   url           190 non-null    object
 3   marked        58 non-null     object
dtypes: datetime64[ns](1), object(3)
memory usage: 17.9+ KB

In [18]:
df_news.head()

  mention_week info  url marked
0   2015-02-16  NaN  NaN    NaN
1   2015-02-23  NaN  NaN    NaN
2   2015-03-02  NaN  NaN    NaN
3   2015-03-09  NaN  NaN    NaN
4   2015-03-16  NaN  NaN    NaN

In [19]:
unique_dates = df_news['mention_week'].sort_values().unique()

# verify all dates are in unique_dates (= that we have data for all weeks)
for date in all_dates:
    if date not in unique_dates:
        print(f"Missing date: {date}")

In [20]:
for date in unique_dates:
    if date not in all_dates:
        print(f"Missing date: {date}")

We discovered that 2 weeks are missing from the GDELT dataset: that's because the service was down for the weeks of 2025-06-16 and 2025-06-23.

To cope with this, we will need to fill in these missing weeks with 0 mentions when we preprocess the data for visualization.

So we will now load all the csv files we use for visualization to add those rows but also to remove the columns we don't need (this way we will have lighter files to load in the dashboard).

## Data cleaning and preprocessing

In [28]:
df_news.head()

  mention_week info  url marked
0   2015-02-16  NaN  NaN    NaN
1   2015-02-23  NaN  NaN    NaN
2   2015-03-02  NaN  NaN    NaN
3   2015-03-09  NaN  NaN    NaN
4   2015-03-16  NaN  NaN    NaN

In [29]:
df_news.to_csv('../data/processed/news_articles_datetime.csv', index=False)