# Racing Bar Chart - Data Analysis Notebook

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json

In [2]:
# Read json files from ../src/json/fips.json
# FIPS 10-4 to Country Name mapping
with open('../src/json/fips.json', 'r') as f:
    fips = json.load(f)

In [3]:
# Function to convert 2-letter FIPS 10-4 country codes to country names
def code_to_country(code):
    try:
        country = fips[code]
        return country
    except:
        raise ValueError(f"Invalid country code: {code}")

In [5]:
# Load src/data/processed/racing_line_chart.csv as pandas dataframe
racing_data = pd.read_csv('../data/processed/racing_line_chart.csv')
racing_data.head()

,mention_week,conflict_continent,conflict_country_name,material_conflict_mentions,material_conflict_unique_events,material_conflict_mentions_weighted
0,2015-02-16,Africa,Algeria,239,153,0.226818
1,2015-02-16,Africa,Angola,23,19,0.531284
2,2015-02-16,Africa,Benin,203,78,0.037963
3,2015-02-16,Africa,Botswana,11,10,1.001831
4,2015-02-16,Africa,Burkina Faso,281,25,0.825964

In [12]:
# Grouping by 'conflict_country_name' create a new column 'cum_material_conflict_mentions' 
# that is the cumulative sum of 'material_conflict_mentions' for that 'conflict_country_name'
racing_data['cum_material_conflict_mentions'] = racing_data.groupby(['conflict_country_name'])['material_conflict_mentions'].cumsum()
racing_data.head()

,mention_week,conflict_continent,conflict_country_name,material_conflict_mentions,material_conflict_unique_events,material_conflict_mentions_weighted,cum_material_conflict_mentions
0,2015-02-16,Africa,Algeria,239,153,0.226818,239
1,2015-02-16,Africa,Angola,23,19,0.531284,23
2,2015-02-16,Africa,Benin,203,78,0.037963,203
3,2015-02-16,Africa,Botswana,11,10,1.001831,11
4,2015-02-16,Africa,Burkina Faso,281,25,0.825964,281

In [13]:
# Showing only the rows where 'conflict_country_name' is 'Syria' orderd by 'mention_week'
racing_data[racing_data['conflict_country_name'] == 'Syria'].sort_values('mention_week')

,mention_week,conflict_continent,conflict_country_name,material_conflict_mentions,material_conflict_unique_events,material_conflict_mentions_weighted,cum_material_conflict_mentions
91,2015-02-16,Asia,Syria,15591,6371,5.426069,15591
285,2015-02-23,Asia,Syria,41214,16107,7.286460,56805
491,2015-03-02,Asia,Syria,28358,12712,5.426148,85163
695,2015-03-09,Asia,Syria,32104,12613,4.702853,117267
906,2015-03-16,Asia,Syria,25295,10164,3.802613,142562
...,...,...,...,...,...,...,...
112788,2025-12-15,Asia,Syria,8364,3119,2.734795,9478375
112974,2025-12-22,Asia,Syria,6788,2669,4.901897,9485163
113154,2025-12-29,Asia,Syria,2337,1260,0.908163,9487500
113345,2026-01-05,Asia,Syria,8159,3880,4.956899,9495659
113533,2026-01-12,Asia,Syria,3905,2380,2.678384,9499564

In [14]:
racing_data['cum_material_conflict_mentions_weighted'] = racing_data.groupby(['conflict_country_name'])['material_conflict_mentions_weighted'].cumsum()
racing_data['cum_material_conflict_unique_events'] = racing_data.groupby(['conflict_country_name'])['material_conflict_unique_events'].cumsum()

In [15]:
racing_data.head()

,mention_week,conflict_continent,conflict_country_name,material_conflict_mentions,material_conflict_unique_events,material_conflict_mentions_weighted,cum_material_conflict_mentions,cum_material_conflict_mentions_weighted,cum_material_conflict_unique_events
0,2015-02-16,Africa,Algeria,239,153,0.226818,239,0.226818,153
1,2015-02-16,Africa,Angola,23,19,0.531284,23,0.531284,19
2,2015-02-16,Africa,Benin,203,78,0.037963,203,0.037963,78
3,2015-02-16,Africa,Botswana,11,10,1.001831,11,1.001831,10
4,2015-02-16,Africa,Burkina Faso,281,25,0.825964,281,0.825964,25

In [16]:
racing_data[racing_data['conflict_country_name'] == 'Syria'].sort_values('mention_week')

,mention_week,conflict_continent,conflict_country_name,material_conflict_mentions,material_conflict_unique_events,material_conflict_mentions_weighted,cum_material_conflict_mentions,cum_material_conflict_mentions_weighted,cum_material_conflict_unique_events
91,2015-02-16,Asia,Syria,15591,6371,5.426069,15591,5.426069,6371
285,2015-02-23,Asia,Syria,41214,16107,7.286460,56805,12.712529,22478
491,2015-03-02,Asia,Syria,28358,12712,5.426148,85163,18.138677,35190
695,2015-03-09,Asia,Syria,32104,12613,4.702853,117267,22.841531,47803
906,2015-03-16,Asia,Syria,25295,10164,3.802613,142562,26.644144,57967
...,...,...,...,...,...,...,...,...,...
112788,2025-12-15,Asia,Syria,8364,3119,2.734795,9478375,1861.017852,3640024
112974,2025-12-22,Asia,Syria,6788,2669,4.901897,9485163,1865.919749,3642693
113154,2025-12-29,Asia,Syria,2337,1260,0.908163,9487500,1866.827911,3643953
113345,2026-01-05,Asia,Syria,8159,3880,4.956899,9495659,1871.784810,3647833
113533,2026-01-12,Asia,Syria,3905,2380,2.678384,9499564,1874.463194,3650213

In [17]:
# Drop the columns 'material_conflict_mentions', 'material_conflict_mentions_weighted', 'material_conflict_unique_events'
racing_data = racing_data.drop(columns=['material_conflict_mentions', 'material_conflict_mentions_weighted', 'material_conflict_unique_events'])

In [18]:
# Rename the columns to 'material_conflict_mentions', 'material_conflict_mentions_weighted', 'material_conflict_unique_events' respectively
racing_data = racing_data.rename(columns={
    'cum_material_conflict_mentions': 'material_conflict_mentions',
    'cum_material_conflict_mentions_weighted': 'material_conflict_mentions_weighted',
    'cum_material_conflict_unique_events': 'material_conflict_unique_events'
})

In [19]:
# Saving the processed dataframe to ../data/processed/racing_bar_chart.csv
racing_data.to_csv('../data/processed/racing_bar_chart.csv', index=False)